version: "3"

services: 
  selenium-hub:
    image: selenium/hub:latest # We can give the specific version also
    container_name: selenium_hub
    privileged: true
    ports:
        - 4444:4444
    volumes:
      - /dev/shm:/dev/shm
      - size='512mb'
    environment:
        GRID_MAX_SESSION: 16
        GRID_BROWSER_TIMEOUT: 30000
        GRID_TIMEOUT: 30000

  chrome:
    image: selenium/node-chrome
    privileged: true
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
      - size='512mb'
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 4
      NODE_MAX_INSTANCES: 3
    
  firefox:
    image: selenium/node-firefox
    privileged: true
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
      - size='512mb'
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 3
      NODE_MAX_INSTANCES: 3
